models/url.py
from config import db, engine
from random import choices
from sqlalchemy.sql import text

class URL(db.Model):
    """URL model for DB"""

    id = db.Column(db.Integer, primary_key = True)
    key = db.Column(db.String(4), nullable = False, unique = True)
    url = db.Column(db.String(), nullable = False)

    def __init__(self, key, url):
        self.key = key
        self.url = url

    def __repr__(self):
        return f'URL({self.key}, {self.url})'

    @staticmethod
    def GenerateKey():
        vals = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
        while True:
            key = "".join(choices(vals, k = 4))
            with engine.connect() as con:
                try:
                    sql = text("SELECT COUNT(1) FROM url WHERE key = :key")
                    res = con.execute(sql, key = key).scalar()
                except:
                    pass

            if not res > 0:
                return key

routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from sqlalchemy.sql import text
from sqlalchemy.exc import SQLAlchemyError
import re

from config import engine, db
from models.url import URL

routes = Blueprint("routes", __name__, static_folder = 'static', template_folder = 'templates')

@routes.errorhandler(404)
def PageNotFound(e):
    return redirect(url_for('routes.Error', title = "Error: 404 - page not found", msg = e))

@routes.route('/')
def Index():
    return render_template("index.html")

@routes.route('/', methods = ['POST'])
def SetURL():
    # Get the url
    url = request.form['url']

    if not url:
        return

    # Define valid url regex
    url_regex = re.compile(
        r'^(?:http)s?://' # http:// or https://
        r'(?:(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)|' #domain...
        r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})' # ...or ip
        r'(?::\d+)?' # optional port
        r'(?:/?|[/?]\S+)$', re.IGNORECASE)

    # Validate the url
    if not url_regex.match(url):
        return render_template("index.html", error = True, urlVal = url)
    
    # Connect to the DB
    with engine.connect() as con:
        # See if there is already a key for the url
        try:
            sql = text("SELECT * FROM url WHERE url = :url")
            res = con.execute(sql, url = url).fetchall()
        except SQLAlchemyError as e:
            return redirect(url_for('routes.Error', title = 'Error: Unhandled error', msg = type(e)))
        except:
            return redirect(url_for('routes.Error', title = 'Error: Unhandled error'))

        # If there is a key display that link
        if len(res) > 0:
            return render_template("index.html", short = f'{request.url_root}{res[0].key}')

        # Generate a new key
        key = URL.GenerateKey()

        try:
            # Insert the KVP into the database
            kvp = URL(key, url)
            db.session.add(kvp)
            db.session.commit()
        except:
            return redirect(url_for('routes.Error', title = 'Error: Unhandled error'))

        # Display the new link from the key
        return render_template("index.html", short = f'{request.url_root}{key}')

@routes.route('/<key>')
def KeyRedir(key):
    # Connect to the DB
    with engine.connect() as con:
        # Get the url associated with the key
        sql = text("SELECT url FROM url WHERE key = :key")
        url = con.execute(sql, key = key).scalar()

    # Redirect to the url for the key
    if url:
        return redirect(url)
    else:
        return redirect(url_for('routes.Error', title = "Error: 404 - page not found", msg = f"The key <{key}> does not exist."))

@routes.route('/error')
def Error():
    # Get the error parameters
    title = request.args.get('title')
    msg = request.args.get('msg')
    back = request.args.get('back')

    return render_template("error.html", title = title, msg = msg, back = back)

templates/_layout.html
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8">
    <meta name="author" content="BLM16">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>{% block title %}{% endblock %} - URL Shortener</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename = 'icons/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename = 'icons/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename = 'icons/favicon-16x16.png') }}">
    <link rel="manifest" type="application/manifest+json" href="{{ url_for('static', filename = 'site.webmanifest') }}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
        integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/styles.css') }}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('routes.Index') }}">
                <img src="{{ url_for('static', filename = 'icons/favicon-32x32.png') }}" width="30" height="30"
                    class="d-inline-block align-top" alt="">
                URL Shortener
            </a>
        </div>
    </nav>

    <div class="top-spacemaker"></div>
    {% block content %}{% endblock %}
    <div class="bottom-spacemaker"></div>

    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

templates/error.html
{% extends "_layout.html" %}
{% block title %}Error{% endblock %}

{% block content %}
    {{ super() }}
    <div class="container">
        <div class="card mx-auto" style="width: 60%;">
            <img src="{{ url_for('static', filename = 'images/error.png') }}" alt="Error" style="height: 40vh;" class="card-image-top mx-auto">
            <div class="card-body text-center">
                <h3 class="card-title">{{ title }}</h3>
                <p>{{ msg }}</p>
                {% if back %}
                    <a href="{{ url_for(back) }}" class="btn btn-info">Go Back</a>
                {% else %}
                    <a href="{{ url_for('routes.Index') }}" class="btn btn-info">Home</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "_layout.html" %}
{% block title %}Home{% endblock %}

{% block content %}
    {{ super() }}
    <div class="splash-bg jumbotron">
        <div class="pt-5">
            <div class="container-fluid col-md-8">
                <form method="post">
                    <label class="sr-only" for="txtURL">URL</label>
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text"><i class="fas fa-link"></i></div>
                        </div>
                        {% if error %}
                        <input class="form-control form-control-lg is-invalid" type="text" name="url" value="{{ urlVal }}" id="txtURL" placeholder="URL you wish to shorten . . .">
                        {% else %}
                        <input class="form-control form-control-lg" type="text" name="url" id="txtURL" placeholder="URL you wish to shorten . . .">
                        {% endif %}
                        <div class="input-group-append">
                            <input type="submit" class="btn btn-primary" value="  Go  ">
                        </div>
                    </div>
                </form>
                {% if short %}
                <div class="short-holder">
                    <p style="color: white;"><a class="btn btn-link" href="{{ short }}">{{ short }}</a> - <button class="btn btn-link" onclick="navigator.clipboard.writeText('{{ short }}'); javascript:$(this).addClass('text-success').css('font-weight', 'bold').text('copied!').blur()">copy</button></p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container main">
        <div class="row text-center justify-content-center">
            <div class="col-md-5 pb-3">
                <div class="text-icon-header">
                    <i class="fas fa-link"></i>
                </div>
                URL Shortener takes a URL, gives it a "key" and then redirects https://my_domain.com/key to the original URL. This is useful because it prevents massive URLs from cluttering up documents, emails, or whatever else you are making. Instead, you can just link a nice, short and clean URL that allows you to get your point across while looking proffesional at the same time. Say goodbye to URL cluttered documents and emails!
            </div>
            <div class="col-md-1 pb-3">
            </div>
            <div class="col-md-5 pb-3">
                <div class="text-icon-header">
                    <i class="fas fa-chart-pie"></i>
                </div>
                URL Shortener is useful for buisnesses where they can have short links for all of their services, rather than massive ones that slow down workflow. To make use of URL Shortener for a buisness, clone the <a href="https://github.com/BLM16/URL-Shortener">repository from GitHub</a>, configure it to your liking, and host it on your own domain. https://your_buisness.com/products/chairs/white_chairs/45651513213213 can be redirected to with https://short_domain.com/a8rt.
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/nav_scroll.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename = 'js/input_validator.js') }}"></script>
{% endblock %}